# Generated by Django 2.1.3 on 2018-11-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerrosRescatados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fotografia', models.ImageField(upload_to='Usuarios/media/imagenesPerros/')),
                ('NombrePerro', models.CharField(max_length=200)),
                ('RazaPredominante', models.CharField(max_length=200)),
                ('Descripcion', models.TextField()),
                ('Estado', models.CharField(choices=[('R', 'Rescatado'), ('D', 'Disponible'), ('A', 'Adoptado')], default='R', max_length=1)),
            ],
        ),
    ]
